export const labels = {
  nav: {
    home: "หน้าแรก",
    policies: "นโยบาย",
    about: "เกี่ยวกับผู้สมัคร",
    video: "วิดีโอแนะนำตัว",
    faq: "คำถามที่พบบ่อย",
    feedback: "เสนอความคิดเห็น",
  },
  common: {
    candidate: "ผู้สมัครหมายเลข",
    share: "แชร์เว็บหาเสียง",
    shareCopied: "คัดลอกลิงก์แล้ว",
  },
  home: {
    policiesCta: "ดูนโยบาย",
    aboutCta: "รู้จักธิติ",
    feedbackCta: "เสนอความคิดเห็น",
    policyTitle: "นโยบายที่อยากทำจริง",
    policySubtitle: "เรื่องใกล้ตัวนักเรียนที่ควรถูกแก้",
    viewAllPolicies: "ดูนโยบายทั้งหมด",
    videoTitle: "วิดีโอแนะนำตัว",
    videoWatch: "ดูวิดีโอแนะนำตัว",
    faqTitle: "คำถามที่พบบ่อย",
  },
  countdown: {
    title: "นับถอยหลังถึงวันเลือกตั้ง",
    days: "วัน",
    hours: "ชั่วโมง",
    minutes: "นาที",
    seconds: "วินาที",
  },
  policies: {
    title: "นโยบายของธิติ",
    subtitle: "ไอเดียที่เริ่มจากปัญหาที่นักเรียนเจอจริง",
    search: "ค้นหานโยบาย...",
    all: "ทั้งหมด",
    impact: "จะช่วยอะไรได้บ้าง",
    readMore: "อ่านเพิ่ม",
    readLess: "ย่อ",
    noResults: "ยังไม่เจอนโยบายที่ตรงกับคำค้นนี้",
  },
  about: {
    subtitle: "ทำความรู้จักหมายเลข 2",
    mission: "สิ่งที่อยากทำ",
    vision: "ภาพโรงเรียนที่อยากเห็น",
    ideology: "แนวคิด",
    reason: "ทำไมถึงลงสมัคร",
  },
  video: {
    title: "วิดีโอแนะนำตัว",
    subtitle: "ฟังจากธิติว่าอยากทำอะไรให้โรงเรียน",
    placeholder: "ยังไม่มีวิดีโอ",
    placeholderSub: "ถ้าอัปเดตวิดีโอแล้ว จะแสดงตรงนี้ทันที",
  },
  feedback: {
    title: "เสนอความคิดเห็น",
    subtitle: "มีปัญหาอะไรในโรงเรียน หรือมีไอเดียอะไร ลองบอกมาได้เลย",
    name: "ชื่อเล่น",
    namePlaceholder: "ไม่ใส่ก็ได้",
    grade: "ระดับชั้น",
    gradePlaceholder: "เช่น ม.5/3",
    category: "หมวดหมู่",
    message: "ข้อเสนอแนะ / ปัญหาที่อยากให้แก้",
    messagePlaceholder: "เขียนสิ่งที่อยากให้ช่วยดูหรือแก้ไขได้เลย",
    submit: "ส่งความคิดเห็น",
    success: "ขอบคุณสำหรับความคิดเห็นนะ",
    note: "ความคิดเห็นจะแสดงบนบอร์ดสาธารณะ เพื่อให้เพื่อน ๆ กดเห็นด้วยได้",
  },
  admin: {
    login: "เข้าสู่ระบบผู้สมัคร",
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    loginButton: "เข้าสู่ระบบ",
    loginError: "ข้อมูลไม่ถูกต้อง ลอง admin / admin123",
    dashboard: "แดชบอร์ด",
    policies: "จัดการนโยบาย",
    candidate: "แก้ไขข้อมูลผู้สมัคร",
    video: "วิดีโอแนะนำตัว",
    feedback: "จัดการความคิดเห็น",
    logout: "ออกจากระบบ",
    save: "บันทึกการเปลี่ยนแปลง",
    saved: "บันทึกแล้ว",
    add: "เพิ่มนโยบาย",
    delete: "ลบ",
    cancel: "ยกเลิก",
    confirmDelete: "ต้องการลบรายการนี้ใช่ไหม?",
    confirmDeleteSub: "ลบแล้วจะย้อนกลับไม่ได้นะ",
  },
} as const;
